parameter_defaults:
    ControlPlaneDefaultRoute: 192.168.24.1
    ControlPlaneSubnetCidr: '24'
    DnsServers:
    - 192.168.24.1
    EC2MetadataIp: 192.168.24.1
    ExternalAllocationPools:
    -   end: 172.18.0.150
        start: 172.18.0.50
    ExternalInterfaceDefaultRoute: 172.18.0.1
    ExternalNetCidr: 172.18.0.0/16
    ExternalNetworkVlanID: 300
    InternalApiAllocationPools:
    -   end: 172.17.1.149
        start: 172.17.1.10
    InternalApiNetCidr: 172.17.1.0/24
    InternalApiNetworkVlanID: 301
    NeutronEnableDVR: 'false'
    NeutronNetworkType: vxlan,vlan
    NeutronTunnelTypes: vxlan
    StorageAllocationPools:
    -   end: 172.17.3.149
        start: 172.17.3.10
    StorageMgmtAllocationPools:
    -   end: 172.17.4.149
        start: 172.17.4.10
    StorageMgmtNetCidr: 172.17.4.0/24
    StorageMgmtNetworkVlanID: 303
    StorageNetCidr: 172.17.3.0/24
    StorageNetworkVlanID: 302
    TenantAllocationPools:
    -   end: 172.17.2.150
        start: 172.17.2.10
    TenantNetCidr: 172.17.2.0/24
    TenantNetworkVlanID: 304

resource_registry:
    OS::TripleO::Controller::Net::SoftwareConfig: vlans//controller-offload.yaml
