parameter_defaults:
    ControlPlaneDefaultRoute: 192.168.24.1
    ControlPlaneSubnetCidr: '24'
    DnsServers:
    - 192.168.24.1
    EC2MetadataIp: 192.168.24.1
    NodeRootPassword: "100yard-"
    SshServerOptions:
        PasswordAuthentication: 'yes'
        PermitRootLogin: 'yes'
resource_registry:
    OS::TripleO::Compute::Net::SoftwareConfig: vlans//compute.yaml
    OS::TripleO::Controller::Net::SoftwareConfig: vlans//controller.yaml
